### ISSUE TITLE
Bug: Crash when rendering [Chevalier Blue] Satono Diamond

### ISSUE THREAD

**Issue by 0999312** [LeadRDRK/umapyoi-fabric#1]
### Describe the bug

Crash when rendering [Chevalier Blue] Satono Diamond
[crash-2024-05-05_00.35.36-client.txt](https://github.com/LeadRDRK/umapyoi-fabric/files/15210399/crash-2024-05-05_00.35.36-client.txt)

### Steps to reproduce

Trying rendering [Chevalier Blue] Satono Diamond, equip it or use Umamusume Wish in three goddesses status.

### Expected behavior

Not crash

### Screenshots

[crash-2024-05-05_00.35.36-client.txt](https://github.com/LeadRDRK/umapyoi-fabric/files/15210400/crash-2024-05-05_00.35.36-client.txt)

### Versions

- Minecraft version: 1.20.1
- Umapyoi version: [Umapyoi Fabricated 1.1.1-1.20.1](https://modrinth.com/mod/umapyoi-fabric/version/1.1.1-1.20.1)

### Additional context

That's a issue in Mysterious Mountain Lib and fixed in newest version, you should fix it too.

**Comment by LeadRDRK** [comment]
Fixed in 75c431710aacaf43fa9361c337cffff29df86085. I've also released v1.1.2 for 1.20.1 and 1.20.4.
